# Generated by Django 2.2.2 on 2019-07-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='Flight_id',
            new_name='flight_id',
        ),
    ]
